### ISSUE TITLE
Monitor array of objects

### ISSUE THREAD

**Issue by sadrzadehsina** [zettajs/zetta-device#24]
Hi,

I am wondering is there any way to monitor an array of objects. I did it like below, but when `consumers` updates with the `add-consumer` endpoint, it does not notify me on the client.

```javascript
function MyDevice() {
  this.consumers = [];
  ...
}

MyDevice.prototype.init = function(config) {
  config
    .monitor('consumers');
  
  config
    .map('add-consumer', this.addConsumer, [{ name: 'consumer', type: 'object' }]);
}

MyDevice.prototype.addConsumer = function( consumer, callback ) {
  this.consumers.push(consumer);
}
```

**Comment by mdobson** [comment]
Unfortunately I don't think that monitoring arrays is currently possible. The magic behind the scenes that makes the functionality work doesn't account for how arrays change. We use some getter/setter magic in javascript to pick up changes about properties. Adding to an array doesn't trigger the setter logic properly, and thus a notification doesn't come through.

Apologies for the issue.

-Matt

**Comment by sadrzadehsina** [comment]
@mdobson thanks for your response.

The point is if I use push functionality in order to fill the array it does not work. But it works if I change `add-consumer` method like below.

```javascript
MyDevice.prototype.addConsumer = function( consumer, callback ) {
  this.consumers = this.consumers.concat([consumer]);
}
```

I am not sure it is an efficient way of filling array or not. But it writes on the stream when the array changes and I can get in on the client.

**Comment by mdobson** [comment]
Not sure on efficiency, but I am also not sure on an alternative method that would also get the stream to trigger.

-Matt

**Comment by AdamMagaluk** [comment]
@sadrzadehsina As Matt mentioned the way arrays work with getters/setters doesn't allow zetta to pick up changes to the underlying objects. You can manually update `this.consumers = ...` or you could use the `config.stream(...)` syntax instead of `config.monitor(...)`. It allows you to explicitly send values down the stream instead of relying on the js getter/setter.

See: https://github.com/zettajs/zetta/wiki/Device#configstreamname-func-options

**Comment by mdobson** [comment]
Ah yes. Configuring the stream in the way Adam describes is the best work around.

-Matt

**Comment by sadrzadehsina** [comment]
@mdobson and @AdamMagaluk thanks, I fixed the issue by using streams, But it would be great if you add the feature of monitoring arrays in the next releases.
